### ISSUE TITLE
Updated B.1.1.7 case count for The Netherlands

### ISSUE THREAD

**Issue by EwoutH** [cov-lineages/lineages-website-old#3]
First of all, huge thanks for this immens effort.

Currently the [B.1.1.7 global report](https://cov-lineages.org/global_report_B.1.1.7.html) states 8 cases in The Netherlands, as of December 28th this is 11 confirmed cases unfortunately.

Source: https://www.rivm.nl/en/news/spread-of-uk-coronavirus-variant-in-netherlands

> The UK variant of the coronavirus (SARS-CoV-2) has been found in 11 people in the Netherlands so far: 5 people in the Amsterdam region, 5 people in the Rotterdam region and 1 person in the Nijmegen region.

For future reference, I tried finding the correct spot in the code to update this data to open a PR, but couldn't find it. Were is this data stored?

**Comment by aineniamh** [comment]
Hi @EwoutH, thanks for getting in touch! The count information in the report I'm currently using is just the counts of sequences on GISAID, and there is a slight lag I think between them going into the database and my being able to download the sequences in bulk (less than 24 hours, but still a slight delay). 

For the import reports of B.1.1.7, which we're reporting imports only or local spread. We're hosting this csv here: https://github.com/cov-lineages/lineages-website/blob/master/_data/Local_Imported_b117.csv. If there's any information that's incorrect (such as date of earliest report, or a different source etc), feel free to correct us. We just have found what information we can online! 

If we move towards reporting sequence counts off of GISAID too, I will include this report- but currently we're just using GISAID counts (this is why the UK count is also slightly lower than the UK count available on CLIMB due to the lag uploading to GISAID).

**Comment by EwoutH** [comment]
Thanks for the reply and extensive explanation!
